### PR TITLE
i18n: Add more translatable fields

### LINKED ISSUE #1363: Wrong title/name
### Observed/problematic behavior

The name of the languages options in the settings is wrong
image

### Expected behavior

It should say something like 'Languages"

### Steps to reproduce

Go to Settings
Go to Other

### Other

_No response_

### PR DESCRIPTION
**Pull request by Leguan16**
- [x] https://hangar.papermc.io/auth/settings/security
- [x] https://hangar.papermc.io/auth/settings/profile
- [x] https://hangar.papermc.io/auth/settings/account
- [x] https://hangar.papermc.io/auth/settings/other

Also fixes missing property for 
image

fixes #1363

### CODE REVIEW

**Comment by Leguan16** [comment]
i added all fields I found. So ready for review.

File: frontend/src/pages/auth/settings/security.vue [hunk 1]
```diff
@@ -339,37 +353,42 @@ function closeUnlinkModal() {
         :disabled="!settings?.hasPassword && settings?.oauthConnections.length === 1"
         :title="
           !settings?.hasPassword && settings?.oauthConnections.length === 1
-            ? 'You can\'t unlink your last oauth credential if you don\'t have a password set'
+            ? // ? t('auth.settings.security.unlinkOAuth.cantUnlink') Doesn't work
```
Comment (MiniDigger) [inline frontend/src/pages/auth/settings/security.vue:356]: will take a look at this after merging

**Comment by MiniDigger** [comment]
thanks!
